const FEED='https://public.api.bsky.app/xrpc/app.bsky.feed.searchPosts';
const HOURS_72=72*60*60*1000;
const LIVE_MINUTES=20;
const QUERIES=[
 'geopolitics OR diplomacy OR ceasefire OR sanctions OR war',
 'election OR parliament OR bill OR referendum OR government reform',
 'NATO OR Ukraine OR Russia OR Israel OR Iran OR Taiwan OR China',
 'border dispute OR coup OR protest OR mobilization OR treaty',
 'nuclear OR IAEA OR missile OR drone OR military',
 'attack OR attacked OR assault OR ambush OR bombing OR explosion OR blast',
 'shooting OR gunfire OR shots fired OR shooter OR armed attack',
 'threat OR threatened OR threat warning OR security alert',
 'robbery OR armed robbery OR theft OR looting OR raid',
 'kidnapping OR abducted OR hostage OR hijacking',
 'clash OR clashes OR fighting OR firefight OR violence OR unrest',
 'terror attack OR terrorism OR extremist OR insurgent OR militant',
 'airstrike OR artillery OR shelling OR mortar OR rocket attack',
 'police attack OR security forces OR military checkpoint OR border incident'
];
const GEO=[
 ['ukraine','Ukraine',48.3794,31.1656],['kyiv','Ukraine',50.4501,30.5234],['kharkiv','Ukraine',49.9935,36.2304],['odesa','Ukraine',46.4825,30.7233],['odessa','Ukraine',46.4825,30.7233],
 ['russia','Russia',61.5240,105.3188],['moscow','Russia',55.7558,37.6173],['belgorod','Russia',50.5954,36.5873],
 ['israel','Israel',31.0461,34.8516],['gaza','Palestine',31.5017,34.4668],['west bank','Palestine',31.9474,35.3027],['iran','Iran',32.4279,53.6880],['tehran','Iran',35.6892,51.3890],
 ['taiwan','Taiwan',23.6978,120.9605],['taipei','Taiwan',25.0330,121.5654],['china','China',35.8617,104.1954],['beijing','China',39.9042,116.4074],['lebanon','Lebanon',33.8547,35.8623],['beirut','Lebanon',33.8938,35.5018],
 ['syria','Syria',34.8021,38.9968],['damascus','Syria',33.5138,36.2765],['yemen','Yemen',15.5527,48.5164],['sanaa','Yemen',15.3694,44.1910],['sudan','Sudan',12.8628,30.2176],['khartoum','Sudan',15.5007,32.5599],
 ['venezuela','Venezuela',6.4238,-66.5897],['caracas','Venezuela',10.4806,-66.9036],['guyana','Guyana',4.8604,-58.9302],['poland','Poland',51.9194,19.1451],
 ['india','India',20.5937,78.9629],['new delhi','India',28.6139,77.2090],['pakistan','Pakistan',30.3753,69.3451],['islamabad','Pakistan',33.6844,73.0479],
 ['north korea','North Korea',40.3399,127.5101],['pyongyang','North Korea',39.0392,125.7625],['south korea','South Korea',35.9078,127.7669],['seoul','South Korea',37.5665,126.9780],['japan','Japan',36.2048,138.2529],['tokyo','Japan',35.6762,139.6503],
 ['colombia','Colombia',4.5709,-74.2973],['bogota','Colombia',4.7110,-74.0721],['bogotá','Colombia',4.7110,-74.0721],['medellin','Colombia',6.2442,-75.5812],['medellín','Colombia',6.2442,-75.5812],['manizales','Colombia',5.0703,-75.5138],
 ['mexico','Mexico',23.6345,-102.5528],['méxico','Mexico',23.6345,-102.5528],['mexico city','Mexico',19.4326,-99.1332],['miami','United States',25.7617,-80.1918],['washington','United States',38.9072,-77.0369],['new york','United States',40.7128,-74.0060],
 ['london','United Kingdom',51.5072,-0.1276],['paris','France',48.8566,2.3522],['berlin','Germany',52.5200,13.4050],['brussels','Belgium',50.8503,4.3517]
];
const ACTORS={NATO:['nato'],Ukraine:['ukraine','kyiv'],Russia:['russia','moscow','kremlin'],Israel:['israel','idf'],Iran:['iran','tehran','irgc'],China:['china','beijing','pla'],Taiwan:['taiwan'],USA:['united states','white house','pentagon','washington'],EU:['european union','brussels'],UN:['united nations','un '],India:['india'],Pakistan:['pakistan'],Police:['police','law enforcement'],Military:['military','armed forces','army'],Militants:['militant','insurgent','extremist'],Civilians:['civilian','residents','people']};
function strip(s=''){return String(s).replace(/\s+/g,' ').trim()}
function family(t){t=t.toLowerCase();if(/threat|threatened|security alert|warning of attack/.test(t))return'threat-warning';if(/shooting|gunfire|shots fired|shooter|armed attack/.test(t))return'armed-violence';if(/robbery|armed robbery|theft|looting|raid/.test(t))return'crime-robbery';if(/kidnap|abduct|hostage|hijack/.test(t))return'kidnapping-hostage';if(/terror|terrorism|extremist|insurgent|militant/.test(t))return'terror-security';if(/explosion|blast|bombing|bomb exploded/.test(t))return'explosion-bombing';if(/clash|fighting|firefight|violence|unrest/.test(t))return'clash-violence';if(/airstrike|artillery|shelling|mortar|rocket|missile|drone|attack|assault|ambush|strike|war|invasion|mobilization/.test(t))return'conflict-escalation';if(/ceasefire|peace|talks|summit|treaty|diplomac/.test(t))return'diplomacy';if(/election|vote|referendum|parliament|bill|legislation|reform/.test(t))return'political-reform';if(/sanction|tariff|embargo|trade/.test(t))return'sanctions-trade';if(/protest|riot|coup/.test(t))return'protest-unrest';if(/nuclear|iaea|uranium/.test(t))return'nuclear';return'geopolitics-general'}
function incidentState(t){t=t.toLowerCase();if(/alleged|reportedly|unconfirmed|rumor|rumour|claim(?:s|ed)?/.test(t))return'REPORTED';if(/threat|threatened|warning|alert/.test(t)&&!/attack(?:ed)?|shooting|explosion|blast|robbery|kidnap|clash|strike/.test(t))return'THREAT';return'OBSERVED-REPORT'}
function geo(text){const t=text.toLowerCase();for(const [k,c,lat,lng] of GEO)if(t.includes(k))return{country:c,locationLabel:k.replace(/\b\w/g,x=>x.toUpperCase()),lat,lng,geoConfidence:.72,geoPrecision:k===c.toLowerCase()?'country':'city'};return{}}
function actors(text){const t=text.toLowerCase();return Object.entries(ACTORS).filter(([,ks])=>ks.some(k=>t.includes(k))).map(([a])=>a)}
function severity(t,f){t=t.toLowerCase();let s=2;if(f==='threat-warning')s+=2;if(/attack|assault|ambush|shooting|gunfire|explosion|blast|bombing|airstrike|artillery|shelling|missile|drone/.test(t))s+=4;if(/killed|dead|fatal|mass casualty|multiple victims/.test(t))s+=2;if(/nuclear|terror|hostage|kidnap|coup|mobilization/.test(t))s+=2;if(/robbery|looting|theft/.test(t))s+=1;return Math.min(10,s)}
function threatType(f){return({'threat-warning':'THREAT','armed-violence':'SHOOTING/ARMED ATTACK','crime-robbery':'ROBBERY/CRIME','kidnapping-hostage':'KIDNAPPING/HOSTAGE','terror-security':'TERROR/SECURITY','explosion-bombing':'EXPLOSION/BOMBING','clash-violence':'CLASH/VIOLENCE','conflict-escalation':'CONFLICT/ATTACK'})[f]||'GEOPOLITICAL'}
async function searchPage(q,cursor=''){const u=new URL(FEED);u.searchParams.set('q',q);u.searchParams.set('limit','100');u.searchParams.set('sort','latest');if(cursor)u.searchParams.set('cursor',cursor);const r=await fetch(u,{headers:{accept:'application/json','user-agent':'GHOTAM/1.2'}});if(!r.ok)throw new Error(`Bluesky ${r.status}`);return r.json()}
async function search72h(q){const cutoff=Date.now()-HOURS_72;const posts=[];let cursor='';for(let page=0;page<8;page++){const d=await searchPage(q,cursor);const batch=Array.isArray(d?.posts)?d.posts:[];posts.push(...batch);if(!batch.length||!d?.cursor)break;const oldest=Math.min(...batch.map(p=>Date.parse(String(p?.record?.createdAt||p?.indexedAt||new Date().toISOString()))).filter(Number.isFinite));if(Number.isFinite(oldest)&&oldest<cutoff)break;cursor=String(d.cursor)}return posts}
export async function handler(){try{const cutoff=Date.now()-HOURS_72;const settled=await Promise.allSettled(QUERIES.map(search72h));const out=[];const seen=new Set();for(const s of settled){if(s.status!=='fulfilled')continue;for(const p of s.value||[]){const rec=p.record||{},text=strip(rec.text||'');if(!text)continue;const ts=Date.parse(String(rec.createdAt||p.indexedAt||''));if(!Number.isFinite(ts)||ts<cutoff)continue;const uri=String(p.uri||'');if(seen.has(uri))continue;seen.add(uri);const g=geo(text),f=family(text),sev=severity(text,f),who=actors(text),state=incidentState(text);const rkey=String(p.author?.handle||p.author?.displayName||'Bluesky');out.push({id:`BSKY:${uri||Math.random()}`,title:text.slice(0,160),description:text,source:`Bluesky · ${rkey}`,feedId:'bluesky',sourceClass:'social',origin:'bluesky',link:p.author?.handle&&uri?`https://bsky.app/profile/${p.author.handle}/post/${uri.split('/').pop()}`:'',publishedAt:new Date(ts).toISOString(),actors:who,tags:['bluesky','social-signal',f,threatType(f).toLowerCase()],category:f.startsWith('crime-')?'security-crime':'security-geopolitics',patternFamily:f,incidentState:state,threatType:threatType(f),severity:sev,interestScore:Math.min(100,sev*10+(who.length*5)+(Number(p.likeCount||0)+Number(p.repostCount||0)>20?10:0)+(g.country?8:0)),tlp:'TLP:CLEAR',socialMetrics:{likes:Number(p.likeCount||0),reposts:Number(p.repostCount||0),replies:Number(p.replyCount||0)},...g});}}
 out.sort((a,b)=>Date.parse(b.publishedAt)-Date.parse(a.publishedAt));const liveCutoff=Date.now()-LIVE_MINUTES*60*1000;const live=out.filter(e=>Date.parse(e.publishedAt)>=liveCutoff);return{statusCode:200,headers:{'content-type':'application/json','cache-control':'no-store'},body:JSON.stringify({updatedAt:new Date().toISOString(),source:'Bluesky public search',windowHours:72,liveMinutes:LIVE_MINUTES,count:out.length,liveCount:live.length,categories:{threats:out.filter(e=>e.patternFamily==='threat-warning').length,attacks:out.filter(e=>['armed-violence','conflict-escalation','explosion-bombing'].includes(e.patternFamily)).length,crime:out.filter(e=>e.patternFamily==='crime-robbery').length},live:live.slice(0,120),events:out.slice(0,1200)})};}catch(e){return{statusCode:500,headers:{'content-type':'application/json'},body:JSON.stringify({error:e instanceof Error?e.message:'Bluesky ingest failed',events:[],live:[]})}}
}
