const CHANNELS=[
  {id:'kyivindependent',name:'The Kyiv Independent',slug:'KyivIndependent_official',language:'en'},
  {id:'entre-guerras',name:'ENTRE GUERRAS',slug:'entre_guerras',language:'es'},
  {id:'mundo-conflicto',name:'Mundo en Conflicto',slug:'MundoEConflicto',language:'es'},
];
const GEO=[
 ['Kyiv','Ukraine',50.4501,30.5234,['kyiv','kiev']],['Ukraine','Ukraine',48.3794,31.1656,['ukraine','ucrania']],['Russia','Russia',61.524,105.3188,['russia','rusia']],['Crimea','Ukraine',45.3,34.0,['crimea']],['Belarus','Belarus',53.7098,27.9534,['belarus','bielorrusia']],['Germany','Germany',51.1657,10.4515,['germany','alemania']],['France','France',46.2276,2.2137,['france','francia']],['Iran','Iran',32.4279,53.688,['iran','irán']],['Israel','Israel',31.0461,34.8516,['israel']],['Yemen','Yemen',15.5527,48.5164,['yemen']],['Saudi Arabia','Saudi Arabia',23.8859,45.0792,['saudi','arabia saudita','saudí']],['Miami','United States',25.7617,-80.1918,['miami']],['Taiwan','Taiwan',23.6978,120.9605,['taiwan']],['China','China',35.8617,104.1954,['china']],['North Korea','North Korea',40.3399,127.5101,['north korea','corea del norte']],['South Korea','South Korea',35.9078,127.7669,['south korea','corea del sur']],['Gaza','Palestinian Territories',31.3547,34.3088,['gaza']],['Lebanon','Lebanon',33.8547,35.8623,['lebanon','líbano']],['Syria','Syria',34.8021,38.9968,['syria','siria']],['Sudan','Sudan',12.8628,30.2176,['sudan','sudán']]
];
const ACTORS=[['Russia',['russia','rusia','russian','ruso']],['Ukraine',['ukraine','ucrania','ukrainian']],['USA',['united states','u.s.','us ','estados unidos','trump']],['NATO',['nato','otan']],['EU',['european union','unión europea','eu ']],['China',['china','chinese']],['Iran',['iran','irán']],['Israel',['israel']],['NorthKorea',['north korea','corea del norte']],['Taiwan',['taiwan']],['Houthis',['houthi','hutí','huties']]];
const decode=s=>String(s||'').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n)));
const strip=s=>decode(String(s||'').replace(/<br\s*\/?>/gi,'\n').replace(/<[^>]+>/g,' ')).replace(/\s+/g,' ').trim();
function extractBlocks(html){return [...html.matchAll(/<div class="tgme_widget_message_wrap[\s\S]*?(?=<div class="tgme_widget_message_wrap|$)/gi)].map(m=>m[0]);}
function classify(text){const t=text.toLowerCase();let severity=3,category='geopolitics';if(/missile|drone attack|strike|bombard|attack|air raid|dead|killed|explosion|derrib|ataque|misil|bombarde/.test(t))severity=8;else if(/nuclear|nuclear deterr|escalat|mobiliz|war|guerra|conflict|conflicto/.test(t))severity=7;else if(/sanction|consulat|diplomat|election|talks|negotiat|acuerdo|elecci|consulado/.test(t))severity=5;if(/cyber|malware|ransomware/.test(t))category='cyber';return{severity,category};}
function geo(text){const t=text.toLowerCase();for(const [label,country,lat,lng,keys] of GEO){if(keys.some(k=>t.includes(k)))return{label,country,lat,lng,confidence:.82}}return null;}
function actors(text){const t=text.toLowerCase();return ACTORS.filter(([,keys])=>keys.some(k=>t.includes(k))).map(([name])=>name);}
function parseChannel(channel,html){const blocks=extractBlocks(html);const out=[];for(const block of blocks){const idMatch=block.match(new RegExp(`https:\\/\\/t\\.me\\/${channel.slug}\\/(\\d+)`,'i'));if(!idMatch)continue;const dt=block.match(/<time[^>]+datetime="([^"]+)"/i)?.[1];const textHtml=block.match(/<div class="tgme_widget_message_text[^>]*>([\s\S]*?)<\/div>/i)?.[1]||'';const body=strip(textHtml);if(!body)continue;const image=block.match(/background-image\s*:\s*url\(['"]([^'"]+)/i)?.[1];const external=block.match(/href="(https?:\/\/(?!t\.me)[^"]+)"/i)?.[1];const loc=geo(body);const c=classify(body);out.push({id:`telegram:${channel.id}:${idMatch[1]}`,title:body.length>150?body.slice(0,147)+'…':body,description:body,link:`https://t.me/${channel.slug}/${idMatch[1]}`,source:channel.name,feedId:`telegram-${channel.id}`,sourceClass:'alternative',origin:'telegram',language:channel.language,publishedAt:dt||new Date().toISOString(),image,externalUrl:external,actors:actors(body),tags:['telegram','alternative-source'],category:c.category,severity:c.severity,interestScore:Math.min(100,c.severity*10+15),geoConfidence:loc?.confidence||0,locationLabel:loc?.label,country:loc?.country,lat:loc?.lat,lng:loc?.lng,locations:loc?[loc]:[],tlp:'TLP:CLEAR'});}return out;}
async function fetchChannel(channel){const ctl=new AbortController();const timer=setTimeout(()=>ctl.abort(),6500);try{const r=await fetch(`https://t.me/s/${channel.slug}`,{signal:ctl.signal,headers:{'user-agent':'Mozilla/5.0 GHOTAM-public-source/1.0','accept':'text/html'}});if(!r.ok)throw new Error(String(r.status));const html=await r.text();const events=parseChannel(channel,html).sort((a,b)=>Date.parse(b.publishedAt)-Date.parse(a.publishedAt)).slice(0,12);return{channel:channel.id,ok:true,count:events.length,events};}catch(e){return{channel:channel.id,ok:false,count:0,error:String(e?.message||e),events:[]};}finally{clearTimeout(timer)}}
export async function handler(){const results=await Promise.all(CHANNELS.map(fetchChannel));const events=results.flatMap(r=>r.events).sort((a,b)=>Date.parse(b.publishedAt)-Date.parse(a.publishedAt));return{statusCode:200,headers:{'content-type':'application/json','cache-control':'public,max-age=60'},body:JSON.stringify({updatedAt:new Date().toISOString(),sourceType:'telegram-public',channelCount:CHANNELS.length,status:results.map(({events,...x})=>x),latest:events.slice(0,5),events})};}
