import { loadCombinedIntel, loadAllIntel, getMemoryValue, setMemoryValue } from './offlineStore';
export type CorpusDocument={id:string;source:string;sourceClass:string;publishedAt:string;title:string;text:string;country?:string;location?:string;lat?:number;lng?:number;actors:string[];tags:string[];category:string;severity:number;interestScore:number;tlp:string;url?:string;image?:string};
export type CorpusSnapshot={schema:'GHOTAM_CORPUS_V1';createdAt:string;count:number;documents:CorpusDocument[]};
const text=(v:any)=>typeof v==='string'?v:'';const arr=(v:any)=>Array.isArray(v)?v.filter((x:any)=>typeof x==='string'):[];
export function toCorpusDocument(e:any,i=0):CorpusDocument{return{id:String(e?.id||`event-${i}`),source:text(e?.source)||text(e?.feedId)||'Unknown',sourceClass:text(e?.sourceClass)||((text(e?.origin)==='telegram')?'alternative':'direct'),publishedAt:text(e?.publishedAt)||new Date().toISOString(),title:text(e?.title)||'Untitled event',text:[text(e?.title),text(e?.description)].filter(Boolean).join('\n\n'),country:text(e?.country)||undefined,location:text(e?.locationLabel)||[e?.zone,e?.city,e?.country].filter(Boolean).join(', ')||undefined,lat:Number.isFinite(Number(e?.lat))?Number(e.lat):undefined,lng:Number.isFinite(Number(e?.lng))?Number(e.lng):undefined,actors:arr(e?.actors),tags:arr(e?.tags),category:text(e?.category)||'world',severity:Number(e?.severity)||1,interestScore:Number(e?.interestScore)||0,tlp:text(e?.tlp)||'TLP:CLEAR',url:text(e?.link)||undefined,image:text(e?.image)||undefined};}
export async function buildCorpus(allSources=true):Promise<CorpusSnapshot>{const raw=allSources?await loadAllIntel(false):await loadCombinedIntel(false);const documents=raw.map(toCorpusDocument);const snap:CorpusSnapshot={schema:'GHOTAM_CORPUS_V1',createdAt:new Date().toISOString(),count:documents.length,documents};await setMemoryValue('corpus-latest',snap).catch(()=>{});return snap;}
export async function getLatestCorpus(){return getMemoryValue<CorpusSnapshot>('corpus-latest')}
function tokenize(s:string){return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').split(/[^a-z0-9ñ]+/).filter(x=>x.length>2)}
export function retrieveCorpus(query:string,docs:CorpusDocument[],limit=12){const q=new Set(tokenize(query));return docs.map(d=>{const hay=tokenize([d.title,d.text,d.country,d.location,...d.actors,...d.tags].filter(Boolean).join(' '));let hits=0;hay.forEach(t=>{if(q.has(t))hits++});const actorBoost=d.actors.some(a=>query.toLowerCase().includes(a.toLowerCase()))?4:0;const geoBoost=(d.country&&query.toLowerCase().includes(d.country.toLowerCase()))?3:0;return{doc:d,score:hits+actorBoost+geoBoost+d.interestScore/100};}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,limit)}
export async function rememberQuery(query:string,answer:string,docIds:string[]){const history=await getMemoryValue<any[]>('query-memory').catch(()=>[])||[];history.unshift({id:`Q-${Date.now()}`,query,answer,docIds,at:new Date().toISOString()});await setMemoryValue('query-memory',history.slice(0,80));}
export async function getQueryMemory(){return await getMemoryValue<any[]>('query-memory').catch(()=>[])||[]}
export function downloadJson(name:string,data:any){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export function downloadJsonl(name:string,docs:CorpusDocument[]){const blob=new Blob([docs.map(d=>JSON.stringify(d)).join('\n')],{type:'application/x-ndjson'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
