import type { DashboardStats,Event,Facility,GraphData,Person,RiskCase,SearchResult,TimelineEvent } from '../types';
import { analyzeAll } from './analysisEngine';
import { loadCombinedIntel } from './offlineStore';

const arr=(v:unknown):string[]=>Array.isArray(v)?v.filter(x=>typeof x==='string').map(String):[];
const num=(v:unknown,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const text=(v:unknown,f='')=>typeof v==='string'&&v.trim()?v.trim():f;
const loc=(e:any)=>{const p=Array.isArray(e?.locations)&&e.locations[0]?e.locations[0]:null;return{lat:typeof e?.lat==='number'?e.lat:typeof p?.lat==='number'?p.lat:undefined,lng:typeof e?.lng==='number'?e.lng:typeof p?.lng==='number'?p.lng:undefined,label:text(e?.locationLabel,text(p?.label,text(e?.city,text(e?.zone,text(e?.country))))),country:text(e?.country,text(p?.country))}};
const eventType=(e:any)=>{const c=text(e?.category).toLowerCase();if(c==='cyber')return'CyberAlert';if(c==='economics')return'Economic';if(c==='policy'||c==='institutions')return'Policy';if(c==='geopolitics')return'Geopolitical';if(c==='world')return'World';return text(e?.feedId,'OpenSourceIntel')};
const sev=(v:any)=>Math.max(0,Math.min(5,Math.ceil(Math.max(0,Math.min(10,num(v,1)))/2)));

export async function getCombinedEvents(params?:{eventType?:string;minSeverity?:number;severity?:number;facilityId?:string}):Promise<Event[]>{
 let out=(await loadCombinedIntel()).map((e:any,i)=>{const l=loc(e),actors=arr(e?.actors);return{eventId:text(e?.id,`LIVE-${i}`),eventType:eventType(e),description:text(e?.title,text(e?.description,'Event')),severity:sev(e?.severity),timestamp:text(e?.publishedAt,new Date().toISOString()),facilityId:l.label?`LOC:${l.label}`:undefined,facilityName:l.label||l.country||undefined,personId:actors[0]?`ACTOR:${actors[0]}`:undefined,personName:actors[0],metadata:{source:text(e?.source,text(e?.feedId,'RSS')),sourceUrl:text(e?.link),image:text(e?.image),country:l.country,actors,tags:arr(e?.tags),interestScore:num(e?.interestScore),geoConfidence:num(e?.geoConfidence),tlp:text(e?.tlp,'TLP:CLEAR'),raw:e}} as Event});
 if(params?.eventType)out=out.filter(e=>e.eventType===params.eventType);if(typeof params?.minSeverity==='number')out=out.filter(e=>e.severity>=params.minSeverity!);if(typeof params?.severity==='number')out=out.filter(e=>e.severity===params.severity);if(params?.facilityId)out=out.filter(e=>e.facilityId===params.facilityId);return out;
}

export async function getCombinedFacilities():Promise<Facility[]>{const raw=await loadCombinedIntel();const m=new Map<string,{label:string;lat:number;lng:number;sevs:number[];actors:Set<string>;sources:Set<string>}>();for(const e of raw){const l=loc(e);if(typeof l.lat!=='number'||typeof l.lng!=='number')continue;const k=`${l.label||l.country}|${l.lat.toFixed(4)}|${l.lng.toFixed(4)}`;const x=m.get(k)||{label:l.label||l.country||'Location',lat:l.lat,lng:l.lng,sevs:[],actors:new Set(),sources:new Set()};x.sevs.push(num(e.severity,1));arr(e.actors).forEach(a=>x.actors.add(a));x.sources.add(text(e.source,text(e.feedId,'RSS')));m.set(k,x)}return[...m.values()].map((x,i)=>{const max=Math.max(1,...x.sevs);return{facilityId:`LOC-${i+1}`,name:x.label,type:'OpenSourceLocation',status:'Observed',criticality:max>=8?'CRITICAL':max>=6?'HIGH':max>=4?'MEDIUM':'LOW',latitude:x.lat,longitude:x.lng,sensorCount:x.sources.size,assetCount:x.actors.size} as Facility})}
export async function getCombinedPersons():Promise<Person[]>{const m=new Map<string,number>();(await loadCombinedIntel()).forEach(e=>arr(e.actors).forEach(a=>m.set(a,(m.get(a)||0)+1)));return[...m.entries()].map(([name,count],i)=>({personId:`ACTOR-${i+1}`,name,role:`Mentioned in ${count} event${count===1?'':'s'}`,clearance:'PUBLIC',personType:'Actor',organizationId:undefined,organizationName:undefined} as Person))}
export async function getCombinedRiskCases():Promise<RiskCase[]>{const analyzed=analyzeAll(await loadCombinedIntel());return analyzed.filter(x=>x.analysis.riskScore>=4.5).sort((a,b)=>b.analysis.riskScore-a.analysis.riskScore).slice(0,120).map(({event,analysis})=>({caseId:`LIVECASE:${event.id}`,title:event.title,status:analysis.riskScore>=6.5?'Open':'Monitoring',confidence:analysis.confidence,riskScore:analysis.riskScore,description:event.description||`${event.source} · ${event.locationLabel||event.country||'sin ubicación'}`,createdAt:event.publishedAt,facilityName:event.locationLabel||event.country||undefined,linkedEventsCount:1,linkedPersonNames:event.actors} as RiskCase))}

function addNode(nodes:GraphData['nodes'],id:string,label:string,type:string,properties:Record<string,unknown>={}){if(!nodes.some(n=>n.id===id))nodes.push({id,label,type,properties})}
function addEdge(edges:GraphData['edges'],source:string,target:string,type:string){const id=`${source}|${type}|${target}`;if(!edges.some(e=>e.id===id))edges.push({id,source,target,type,properties:{}})}
export async function getCombinedGraph(nodeId:string|null,depth=2):Promise<GraphData>{const raw=await loadCombinedIntel();const nodes:GraphData['nodes']=[],edges:GraphData['edges']=[];const wanted=(nodeId||'').replace(/^LIVECASE:/,'');let matches=raw.filter((e:any)=>text(e.id)===wanted||`EVENT:${text(e.id)}`===nodeId);if(!matches.length&&nodeId?.startsWith('ACTOR:')){const a=nodeId.slice(6);matches=raw.filter((e:any)=>arr(e.actors).includes(a))}if(!matches.length&&nodeId?.startsWith('LOC:')){const q=nodeId.slice(4);matches=raw.filter((e:any)=>{const l=loc(e);return l.label===q||l.country===q})}if(!matches.length)matches=raw.slice(0,depth>1?30:12);matches.slice(0,40).forEach((e:any,i)=>{const eid=`EVENT:${text(e.id,String(i))}`,source=text(e.source,text(e.feedId,'RSS')),sid=`SOURCE:${source}`,l=loc(e);addNode(nodes,eid,text(e.title,'Event').slice(0,120),'Event',{severity:num(e.severity),publishedAt:e.publishedAt,link:e.link,sourceEventId:text(e.id)});addNode(nodes,sid,source,'Source',{});addEdge(edges,eid,sid,'PUBLISHED_BY');arr(e.actors).slice(0,8).forEach(a=>{const aid=`ACTOR:${a}`;addNode(nodes,aid,a,'Person',{actor:true});addEdge(edges,eid,aid,'MENTIONS')});if(l.label||l.country){const label=l.label||l.country,lid=`LOC:${label}`;addNode(nodes,lid,label,'Location',{latitude:l.lat,longitude:l.lng,country:l.country});addEdge(edges,eid,lid,'OCCURRED_AT')}});return{nodes,edges}}

export async function getCombinedTimeline(from?:string,to?:string,facilityId?:string):Promise<TimelineEvent[]>{let events=await getCombinedEvents({facilityId});const a=from?Date.parse(from):NaN,b=to?Date.parse(to):NaN;if(Number.isFinite(a))events=events.filter(e=>Date.parse(e.timestamp)>=a);if(Number.isFinite(b))events=events.filter(e=>Date.parse(e.timestamp)<=b);return events.map(e=>({eventId:e.eventId,eventType:e.eventType,description:e.description,severity:e.severity,timestamp:e.timestamp,facilityName:e.facilityName,personName:e.personName}))}
export async function getCombinedDashboardStats():Promise<DashboardStats>{const [events,facilities,persons,cases]=await Promise.all([getCombinedEvents(),getCombinedFacilities(),getCombinedPersons(),getCombinedRiskCases()]);const tm=new Map<string,number>(),sm=new Map<number,number>();events.forEach(e=>{tm.set(e.eventType,(tm.get(e.eventType)||0)+1);sm.set(e.severity,(sm.get(e.severity)||0)+1)});return{totalFacilities:facilities.length,totalEvents:events.length,openCases:cases.length,criticalAlerts:events.filter(e=>e.severity>=4).length,totalPersons:persons.length,eventsByType:[...tm].map(([type,count])=>({type,count})).sort((a,b)=>b.count-a.count),eventsBySeverity:[...sm].map(([severity,count])=>({severity,count})).sort((a,b)=>a.severity-b.severity)}}
export async function searchCombinedIntel(q:string,page=1):Promise<SearchResult>{const raw=await loadCombinedIntel(),needle=q.trim().toLowerCase(),matched=raw.filter((e:any)=>[e.title,e.description,e.source,e.country,e.city,e.zone,e.locationLabel,...arr(e.actors)].join(' ').toLowerCase().includes(needle));const pageSize=20;return{totalCount:matched.length,hits:matched.slice((page-1)*pageSize,page*pageSize).map((e:any,i)=>({id:text(e.id,String(i)),type:eventType(e),description:text(e.title,text(e.description,'Event')),score:Math.max(.1,Math.min(1,num(e.interestScore,50)/100)),sourceType:'event',facilityName:loc(e).label||loc(e).country||undefined,personName:arr(e.actors)[0],sourceFile:text(e.source,text(e.feedId,'RSS')),classification:text(e.tlp,'TLP:CLEAR'),timestamp:text(e.publishedAt)}))}}
