import { filterBySourceMode,getSourceMode } from './sourceMode';
export type ManualIntelEvent={id:string;title:string;description:string;source:string;link:string;publishedAt:string;image?:string;country?:string;city?:string;zone?:string;locationLabel?:string;lat?:number;lng?:number;actors:string[];tags:string[];category:string;severity:number;interestScore:number;geoConfidence:number;tlp:'TLP:CLEAR'|'TLP:GREEN'|'TLP:AMBER'|'TLP:AMBER+STRICT'|'TLP:RED';origin:'manual';status:'published'|'draft';createdAt:string;updatedAt:string;};
const DB='ghotam-offline',VERSION=1,EVENTS='manual-events',KV='kv';
export const OFFLINE_CHANGED='ghotam:offline-events-changed';
const nativeFetch=typeof window!=='undefined'?window.fetch.bind(window):fetch;
function openDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const req=indexedDB.open(DB,VERSION);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(EVENTS))db.createObjectStore(EVENTS,{keyPath:'id'});if(!db.objectStoreNames.contains(KV))db.createObjectStore(KV,{keyPath:'key'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
function done(tx:IDBTransaction){return new Promise<void>((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}
export async function listManualEvents():Promise<ManualIntelEvent[]>{const db=await openDb();return new Promise((resolve,reject)=>{const req=db.transaction(EVENTS,'readonly').objectStore(EVENTS).getAll();req.onsuccess=()=>resolve((req.result||[]).sort((a,b)=>Date.parse(b.publishedAt)-Date.parse(a.publishedAt)));req.onerror=()=>reject(req.error)})}
export async function saveManualEvent(event:ManualIntelEvent){const db=await openDb();const tx=db.transaction(EVENTS,'readwrite');tx.objectStore(EVENTS).put(event);await done(tx);window.dispatchEvent(new Event(OFFLINE_CHANGED));return event}
export async function deleteManualEvent(id:string){const db=await openDb();const tx=db.transaction(EVENTS,'readwrite');tx.objectStore(EVENTS).delete(id);await done(tx);window.dispatchEvent(new Event(OFFLINE_CHANGED))}
export async function replaceManualEvents(events:ManualIntelEvent[]){const db=await openDb();const tx=db.transaction(EVENTS,'readwrite');const store=tx.objectStore(EVENTS);store.clear();events.forEach(e=>store.put(e));await done(tx);window.dispatchEvent(new Event(OFFLINE_CHANGED))}
export async function getMemoryValue<T>(key:string):Promise<T|undefined>{const db=await openDb();return new Promise((resolve,reject)=>{const req=db.transaction(KV,'readonly').objectStore(KV).get(key);req.onsuccess=()=>resolve(req.result?.value as T|undefined);req.onerror=()=>reject(req.error)})}
export async function setMemoryValue(key:string,value:any){const db=await openDb();const tx=db.transaction(KV,'readwrite');tx.objectStore(KV).put({key,value,at:new Date().toISOString()});await done(tx)}
function manualAsIntel(manual:ManualIntelEvent[]){return manual.filter(e=>e.status==='published').map(e=>({...e,feedId:'manual',source:e.source||'GHOTAM Admin',sourceClass:'direct',locations:typeof e.lat==='number'&&typeof e.lng==='number'?[{label:e.locationLabel||e.city||e.zone||e.country||'Manual location',country:e.country,lat:e.lat,lng:e.lng,confidence:e.geoConfidence}]:[]}))}
function dedupeSort(groups:any[][]){const byId=new Map<string,any>();groups.flat().forEach((e,i)=>byId.set(String(e?.id||e?.link||`evt-${i}`),e));return[...byId.values()].sort((a,b)=>Date.parse(String(b.publishedAt||0))-Date.parse(String(a.publishedAt||0)))}
async function loadRemote(path:string,cacheKey:string,force=false){const r=await nativeFetch(path,{headers:{accept:'application/json'},cache:force?'no-store':'default'});const ct=r.headers.get('content-type')||'';if(!r.ok||!ct.includes('application/json'))throw new Error(`${path} ${r.status}`);const d=await r.json();const remote=Array.isArray(d?.events)?d.events:[];await setMemoryValue(cacheKey,remote).catch(()=>{});return remote}
async function loadCached(key:string){const v=await getMemoryValue<any[]>(key).catch(()=>undefined);return Array.isArray(v)?v:[]}
export async function loadAllIntel(force=false):Promise<any[]>{
 const manual=manualAsIntel(await listManualEvents().catch(()=>[]));let direct:any[]=[],alternative:any[]=[],social:any[]=[];
 if(force||navigator.onLine){const [d,a,s]=await Promise.allSettled([loadRemote('/api/rss','rss-cache',force),loadRemote('/api/telegram','telegram-cache',force),loadRemote('/api/bluesky','bluesky-cache',force)]);direct=d.status==='fulfilled'?d.value:await loadCached('rss-cache');alternative=a.status==='fulfilled'?a.value:await loadCached('telegram-cache');social=s.status==='fulfilled'?s.value:await loadCached('bluesky-cache');}
 else{direct=await loadCached('rss-cache');alternative=await loadCached('telegram-cache');social=await loadCached('bluesky-cache');}
 return dedupeSort([direct,manual,alternative,social]);
}
export async function loadCombinedIntel(force=false):Promise<any[]>{return filterBySourceMode(await loadAllIntel(force),getSourceMode())}
let interceptorInstalled=false;
export function installIntelFetchInterceptor(){if(typeof window==='undefined'||interceptorInstalled)return;interceptorInstalled=true;window.fetch=(async(input:RequestInfo|URL,init?:RequestInit)=>{const url=typeof input==='string'?input:input instanceof URL?input.toString():input.url;let parsed:URL;try{parsed=new URL(url,window.location.href)}catch{return nativeFetch(input as any,init)}if(parsed.origin===window.location.origin&&parsed.pathname==='/api/rss'&&(!init?.method||init.method.toUpperCase()==='GET')){const events=await loadCombinedIntel(Boolean(init?.cache==='no-store'));return new Response(JSON.stringify({updatedAt:new Date().toISOString(),offlineAware:true,sourceMode:getSourceMode(),events}),{status:200,headers:{'content-type':'application/json','cache-control':'no-store'}})}return nativeFetch(input as any,init)}) as typeof window.fetch}
export function fileToDataUrl(file:File):Promise<string>{return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||''));r.onerror=()=>reject(r.error);r.readAsDataURL(file)})}
export function makeManualId(){return`MANUAL-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
