import { useEffect,useMemo,useRef,useState } from 'react';
import { Download,Edit3,ImagePlus,LocateFixed,MapPin,Plus,Save,Trash2,Upload,X } from 'lucide-react';
import { MapContainer,TileLayer,CircleMarker,useMapEvents } from 'react-leaflet';
import { deleteManualEvent,fileToDataUrl,listManualEvents,makeManualId,replaceManualEvents,saveManualEvent,type ManualIntelEvent } from '../live/offlineStore';

type FormState={title:string;description:string;source:string;link:string;publishedAt:string;country:string;city:string;zone:string;lat:string;lng:string;actors:string;tags:string;category:string;severity:string;interestScore:string;geoConfidence:string;tlp:ManualIntelEvent['tlp'];status:ManualIntelEvent['status'];image:string};
type GeoResult={displayName:string;lat:number;lng:number;country?:string;city?:string;state?:string};
const nowLocal=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)};
const empty=():FormState=>({title:'',description:'',source:'GHOTAM Admin',link:'',publishedAt:nowLocal(),country:'',city:'',zone:'',lat:'',lng:'',actors:'',tags:'',category:'geopolitics',severity:'5',interestScore:'50',geoConfidence:'0.95',tlp:'TLP:CLEAR',status:'published',image:''});
const split=(s:string)=>s.split(',').map(x=>x.trim()).filter(Boolean);
const n=(s:string)=>{const v=Number(s);return Number.isFinite(v)?v:undefined};
function ClickPicker({onPick}:{onPick:(lat:number,lng:number)=>void}){useMapEvents({click:e=>onPick(Number(e.latlng.lat.toFixed(6)),Number(e.latlng.lng.toFixed(6)))});return null}
function parseCsv(text:string):Record<string,string>[] {
  const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;
  for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell=''}else cell+=c}row.push(cell);if(row.some(x=>x.trim()))rows.push(row);if(rows.length<2)return[];const head=rows[0].map(x=>x.trim());return rows.slice(1).map(r=>Object.fromEntries(head.map((h,i)=>[h,String(r[i]||'').trim()])))
}

export default function AdminEvents(){
  const[events,setEvents]=useState<ManualIntelEvent[]>([]);const[form,setForm]=useState<FormState>(empty());const[editingId,setEditingId]=useState('');const[msg,setMsg]=useState('');const[geoResults,setGeoResults]=useState<GeoResult[]>([]);const[geocoding,setGeocoding]=useState(false);const fileRef=useRef<HTMLInputElement>(null);const importRef=useRef<HTMLInputElement>(null);
  const refresh=()=>listManualEvents().then(setEvents).catch(()=>setEvents([]));useEffect(()=>{refresh()},[]);
  const mapped=useMemo(()=>events.filter(e=>typeof e.lat==='number'&&typeof e.lng==='number').length,[events]);
  const set=(k:keyof FormState,v:string)=>setForm(f=>({...f,[k]:v}));
  const lat=n(form.lat),lng=n(form.lng);const mapCenter:[number,number]=[lat??4.5709,lng??-74.2973];

  async function resolveLocation(){const q=[form.zone,form.city,form.country].filter(Boolean).join(', ');if(!q){setMsg('Escribe zona, ciudad o país antes de resolver la ubicación.');return}if(!navigator.onLine){setMsg('Sin Internet: selecciona el punto directamente en el mapa o escribe coordenadas.');return}setGeocoding(true);setGeoResults([]);try{const r=await fetch(`/api/geocode?q=${encodeURIComponent(q)}`);const d=await r.json();if(!r.ok)throw new Error(d?.error||`Geocode ${r.status}`);const found=Array.isArray(d?.results)?d.results:[];setGeoResults(found);if(found[0]){setForm(f=>({...f,lat:String(found[0].lat),lng:String(found[0].lng),country:f.country||found[0].country||'',city:f.city||found[0].city||'',geoConfidence:'0.95'}));setMsg(`Ubicación resuelta: ${found[0].displayName}`)}else setMsg('No se encontró una ubicación. Prueba ciudad + país o selecciónala en el mapa.')}catch(e){setMsg(e instanceof Error?e.message:'No se pudo resolver la ubicación.')}finally{setGeocoding(false)}}
  async function save(){if(!form.title.trim()){setMsg('El título es obligatorio.');return}const la=n(form.lat),ln=n(form.lng);if((form.lat||form.lng)&&(la===undefined||ln===undefined)){setMsg('Latitud y longitud deben ser números válidos.');return}const existing=events.find(e=>e.id===editingId);const now=new Date().toISOString();const locationLabel=[form.zone,form.city,form.country].filter(Boolean).join(', ');const event:ManualIntelEvent={id:editingId||makeManualId(),title:form.title.trim(),description:form.description.trim(),source:form.source.trim()||'GHOTAM Admin',link:form.link.trim(),publishedAt:new Date(form.publishedAt||Date.now()).toISOString(),image:form.image||undefined,country:form.country.trim()||undefined,city:form.city.trim()||undefined,zone:form.zone.trim()||undefined,locationLabel:locationLabel||undefined,lat:la,lng:ln,actors:split(form.actors),tags:split(form.tags),category:form.category.trim()||'world',severity:Math.max(0,Math.min(10,Number(form.severity)||0)),interestScore:Math.max(0,Math.min(100,Number(form.interestScore)||0)),geoConfidence:Math.max(0,Math.min(1,Number(form.geoConfidence)||0)),tlp:form.tlp,origin:'manual',status:form.status,createdAt:existing?.createdAt||now,updatedAt:now};await saveManualEvent(event);setMsg(editingId?'Evento actualizado.':'Evento creado y publicado localmente.');setEditingId('');setForm(empty());setGeoResults([]);refresh()}
  function edit(e:ManualIntelEvent){setEditingId(e.id);const d=new Date(e.publishedAt);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());setForm({title:e.title,description:e.description,source:e.source,link:e.link,publishedAt:d.toISOString().slice(0,16),country:e.country||'',city:e.city||'',zone:e.zone||'',lat:e.lat?.toString()||'',lng:e.lng?.toString()||'',actors:e.actors.join(', '),tags:e.tags.join(', '),category:e.category,severity:String(e.severity),interestScore:String(e.interestScore),geoConfidence:String(e.geoConfidence),tlp:e.tlp,status:e.status,image:e.image||''});setGeoResults([]);window.scrollTo({top:0,behavior:'smooth'})}
  async function remove(id:string){if(!confirm('¿Eliminar este evento local?'))return;await deleteManualEvent(id);if(editingId===id){setEditingId('');setForm(empty())}refresh()}
  async function photo(file?:File){if(!file)return;if(file.size>5*1024*1024){setMsg('La imagen debe pesar menos de 5 MB.');return}set('image',await fileToDataUrl(file))}
  function exportJson(){const blob=new Blob([JSON.stringify(events,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`ghotam-events-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)}
  async function importFile(file?:File){if(!file)return;try{let data:any[]=[];if(file.name.toLowerCase().endsWith('.csv')){const rows=parseCsv(await file.text());const now=new Date().toISOString();data=rows.map((r,i)=>({id:r.id||makeManualId(),title:r.title||`Imported event ${i+1}`,description:r.description||'',source:r.source||'CSV Import',link:r.link||'',publishedAt:new Date(r.publishedAt||r.date||Date.now()).toISOString(),country:r.country||undefined,city:r.city||undefined,zone:r.zone||undefined,locationLabel:r.locationLabel||[r.zone,r.city,r.country].filter(Boolean).join(', ')||undefined,lat:n(r.lat),lng:n(r.lng),actors:split(r.actors||''),tags:split(r.tags||''),category:r.category||'world',severity:Number(r.severity)||1,interestScore:Number(r.interestScore)||50,geoConfidence:Number(r.geoConfidence)||.8,tlp:(r.tlp||'TLP:CLEAR') as ManualIntelEvent['tlp'],origin:'manual',status:(r.status==='draft'?'draft':'published') as ManualIntelEvent['status'],createdAt:r.createdAt||now,updatedAt:now}));}else{const parsed=JSON.parse(await file.text());if(!Array.isArray(parsed))throw new Error('El JSON debe contener un array.');data=parsed}await replaceManualEvents(data as ManualIntelEvent[]);setMsg(`${data.length} eventos importados.`);refresh()}catch(e){setMsg(e instanceof Error?e.message:'Archivo inválido.')}}

  const field='w-full bg-[#091019] border border-[#273747] px-3 py-2 text-xs text-slate-200 outline-none focus:border-cyan-500/50';
  return <div className="admin-crud animate-slide-in"><div className="intel-page-head"><div><div className="eyebrow">ADMIN / LOCAL DATA ENTRY</div><h2>Event CRUD</h2><p>Crea, edita, elimina e importa eventos. Se guardan en IndexedDB y alimentan mapa, Timeline, Graph, Risk y Dashboard.</p></div><div className="flex gap-2"><button className="intel-action" onClick={exportJson}><Download size={13}/>EXPORT JSON</button><button className="intel-action" onClick={()=>importRef.current?.click()}><Upload size={13}/>IMPORT JSON / CSV</button><input ref={importRef} type="file" accept="application/json,.json,text/csv,.csv" hidden onChange={e=>importFile(e.target.files?.[0])}/></div></div>
    <div className="grid grid-cols-[minmax(0,1.15fr)_minmax(360px,.85fr)] gap-3"><section className="intel-panel"><div className="flex justify-between"><div><div className="eyebrow">EVENT FORM</div><h3>{editingId?'Editar evento':'Nuevo evento'}</h3></div>{editingId&&<button onClick={()=>{setEditingId('');setForm(empty());setGeoResults([])}} className="text-slate-500"><X size={16}/></button>}</div>
      <div className="admin-form-grid mt-4"><label className="col-span-2">Título<input className={field} value={form.title} onChange={e=>set('title',e.target.value)} placeholder="Nombre del evento"/></label><label className="col-span-2">Descripción<textarea className={`${field} min-h-28 resize-y`} value={form.description} onChange={e=>set('description',e.target.value)} placeholder="Qué ocurrió, contexto, evidencia..."/></label><label>Fecha y hora<input type="datetime-local" className={field} value={form.publishedAt} onChange={e=>set('publishedAt',e.target.value)}/></label><label>Categoría<select className={field} value={form.category} onChange={e=>set('category',e.target.value)}><option>geopolitics</option><option>world</option><option>cyber</option><option>economics</option><option>policy</option><option>institutions</option><option>security</option><option>humanitarian</option><option>infrastructure</option><option>other</option></select></label><label>País<input className={field} value={form.country} onChange={e=>set('country',e.target.value)} placeholder="Colombia"/></label><label>Ciudad<input className={field} value={form.city} onChange={e=>set('city',e.target.value)} placeholder="Manizales"/></label><label>Zona / sector<input className={field} value={form.zone} onChange={e=>set('zone',e.target.value)} placeholder="La Enea / Zona Norte"/></label><div className="flex items-end"><button type="button" onClick={resolveLocation} className="admin-secondary w-full"><LocateFixed size={13}/>{geocoding?'RESOLVIENDO...':'RESOLVER UBICACIÓN'}</button></div><label>Latitud<input className={field} value={form.lat} onChange={e=>set('lat',e.target.value)} placeholder="5.0703"/></label><label>Longitud<input className={field} value={form.lng} onChange={e=>set('lng',e.target.value)} placeholder="-75.5138"/></label></div>
      {geoResults.length>1&&<div className="admin-geo-results">{geoResults.slice(0,5).map((g,i)=><button key={`${g.lat}-${g.lng}-${i}`} onClick={()=>{set('lat',String(g.lat));set('lng',String(g.lng));setMsg(`Seleccionado: ${g.displayName}`)}}>{g.displayName}</button>)}</div>}
      <div className="admin-map-picker"><MapContainer key={`${Math.round(mapCenter[0]*100)}-${Math.round(mapCenter[1]*100)}`} center={mapCenter} zoom={lat!==undefined&&lng!==undefined?11:4} className="w-full h-full"><TileLayer url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" attribution=""/><ClickPicker onPick={(la,ln)=>{set('lat',String(la));set('lng',String(ln));set('geoConfidence','1');setMsg(`Coordenadas seleccionadas: ${la}, ${ln}`)}}/>{lat!==undefined&&lng!==undefined&&<CircleMarker center={[lat,lng]} radius={9} pathOptions={{color:'#22d3ee',fillColor:'#22d3ee',fillOpacity:.8}}/>}</MapContainer><div className="admin-map-hint">Haz clic en el mapa para fijar la posición exacta. Funciona offline en zonas previamente cacheadas.</div></div>
      <div className="admin-form-grid mt-3"><label>Severidad 0–10<input type="number" min="0" max="10" step="0.1" className={field} value={form.severity} onChange={e=>set('severity',e.target.value)}/></label><label>Interest Score 0–100<input type="number" min="0" max="100" className={field} value={form.interestScore} onChange={e=>set('interestScore',e.target.value)}/></label><label>Geo confidence 0–1<input type="number" min="0" max="1" step="0.01" className={field} value={form.geoConfidence} onChange={e=>set('geoConfidence',e.target.value)}/></label><label>TLP<select className={field} value={form.tlp} onChange={e=>set('tlp',e.target.value as ManualIntelEvent['tlp'])}><option>TLP:CLEAR</option><option>TLP:GREEN</option><option>TLP:AMBER</option><option>TLP:AMBER+STRICT</option><option>TLP:RED</option></select></label><label>Estado<select className={field} value={form.status} onChange={e=>set('status',e.target.value as ManualIntelEvent['status'])}><option value="published">published</option><option value="draft">draft</option></select></label><label>Fuente<input className={field} value={form.source} onChange={e=>set('source',e.target.value)} placeholder="Observación local / informe"/></label><label className="col-span-2">URL / referencia<input className={field} value={form.link} onChange={e=>set('link',e.target.value)} placeholder="https://... o referencia interna"/></label><label className="col-span-2">Actores <span>separados por coma</span><input className={field} value={form.actors} onChange={e=>set('actors',e.target.value)} placeholder="Actor A, Actor B, Organización C"/></label><label className="col-span-2">Tags <span>separados por coma</span><input className={field} value={form.tags} onChange={e=>set('tags',e.target.value)} placeholder="protesta, energía, seguridad"/></label></div>
      <div className="admin-photo mt-4"><input ref={fileRef} type="file" accept="image/*" hidden onChange={e=>photo(e.target.files?.[0])}/>{form.image?<div className="relative"><img src={form.image} alt="preview"/><button onClick={()=>set('image','')} className="absolute top-2 right-2 bg-black/70 p-1"><X size={14}/></button></div>:<button onClick={()=>fileRef.current?.click()}><ImagePlus size={18}/><span>Subir foto del evento</span><small>JPG, PNG, WEBP · se guarda offline en IndexedDB</small></button>}</div><div className="flex items-center justify-between mt-4"><div className="text-[10px] text-slate-600"><MapPin size={12} className="inline mr-1"/>País/ciudad/zona pueden resolverse online; las coordenadas quedan disponibles offline.</div><button onClick={save} className="admin-primary"><Save size={14}/>{editingId?'GUARDAR CAMBIOS':'CREAR EVENTO'}</button></div>{msg&&<div className="intel-note mt-3">{msg}</div>}</section>
      <section className="intel-panel min-h-[650px]"><div className="flex justify-between"><div><div className="eyebrow">LOCAL DATABASE</div><h3>Eventos manuales</h3></div><div className="text-right"><strong className="text-xl font-mono">{events.length}</strong><div className="text-[8px] text-slate-600">{mapped} MAPPED</div></div></div><div className="admin-event-list mt-4">{events.map(e=><article key={e.id}><div className="flex gap-3">{e.image&&<img src={e.image} alt=""/>}<div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><small>{e.status.toUpperCase()} · {e.tlp}</small><span className="text-[9px] text-slate-600">S{e.severity}</span></div><b>{e.title}</b><p>{[e.zone,e.city,e.country].filter(Boolean).join(' · ')||'Sin ubicación'}</p><div className="flex gap-2 mt-2"><button onClick={()=>edit(e)}><Edit3 size={12}/>Editar</button><button onClick={()=>remove(e.id)} className="text-red-400"><Trash2 size={12}/>Eliminar</button></div></div></div></article>)}{!events.length&&<div className="text-center py-16 text-slate-600"><Plus className="mx-auto mb-2"/>Aún no has creado eventos locales.</div>}</div></section></div></div>;
}
