import { useRiskCases } from '../hooks/useApi';
import { useNavigate } from 'react-router-dom';
import { useState } from 'react';
import { ShieldAlert, Network, User, Building2 } from 'lucide-react';
import Pagination from './Pagination';

export default function CasesView() {
  const { data: cases, isLoading } = useRiskCases();
  const navigate = useNavigate();
  const [page, setPage] = useState(1);
  const PAGE_SIZE = 10;

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="animate-pulse text-cyan-400">Loading risk cases...</div>
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-slide-in">
      <div>
        <h2 className="text-xl font-bold text-gray-100">Risk Cases</h2>
        <p className="text-xs text-gray-500 mt-1">
          Suspected sabotage cases generated by OWL inference rules
        </p>
      </div>

      <div className="grid grid-cols-1 gap-4">
        {cases
          ?.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE)
          .map((c) => (
          <div
            key={c.caseId}
            className="aegis-card aegis-card-hover p-5 cursor-pointer"
            onClick={() => navigate(`/graph/${c.caseId}`)}
          >
            <div className="flex items-start gap-4">
              {/* Risk Score Circle */}
              <div className="relative">
                <svg className="w-16 h-16" viewBox="0 0 36 36">
                  <path
                    className="text-gray-800"
                    strokeWidth="3"
                    fill="none"
                    stroke="currentColor"
                    d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                  />
                  <path
                    className={c.riskScore >= 8 ? 'text-red-500' : c.riskScore >= 6 ? 'text-orange-500' : 'text-yellow-500'}
                    strokeWidth="3"
                    fill="none"
                    stroke="currentColor"
                    strokeDasharray={`${c.riskScore * 10}, 100`}
                    strokeLinecap="round"
                    d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                  />
                </svg>
                <div className="absolute inset-0 flex items-center justify-center">
                  <span className={`text-sm font-bold ${
                    c.riskScore >= 8 ? 'text-red-400' : c.riskScore >= 6 ? 'text-orange-400' : 'text-yellow-400'
                  }`}>
                    {c.riskScore.toFixed(1)}
                  </span>
                </div>
              </div>

              {/* Info */}
              <div className="flex-1">
                <div className="flex items-center gap-3 mb-2">
                  <ShieldAlert className="w-5 h-5 text-red-400" />
                  <h3 className="text-lg font-semibold text-gray-100">{c.title}</h3>
                  <span className={`px-2 py-0.5 rounded text-xs font-medium ${
                    c.status === 'Open' ? 'bg-red-500/10 text-red-400 border border-red-500/30' :
                    c.status === 'Investigating' ? 'bg-yellow-500/10 text-yellow-400 border border-yellow-500/30' :
                    'bg-green-500/10 text-green-400 border border-green-500/30'
                  }`}>
                    {c.status}
                  </span>
                </div>
                <p className="text-sm text-gray-400">{c.description}</p>

                <div className="flex items-center gap-6 mt-3">
                  <div className="flex items-center gap-1.5 text-xs text-gray-500">
                    <Network className="w-3.5 h-3.5" />
                    {c.linkedEventsCount} linked events
                  </div>
                  {c.facilityName && (
                    <div className="flex items-center gap-1.5 text-xs text-gray-500">
                      <Building2 className="w-3.5 h-3.5" />
                      {c.facilityName}
                    </div>
                  )}
                  {c.linkedPersonNames.length > 0 && (
                    <div className="flex items-center gap-1.5 text-xs text-gray-500">
                      <User className="w-3.5 h-3.5" />
                      {c.linkedPersonNames.join(', ')}
                    </div>
                  )}
                </div>

                {/* Confidence bar */}
                <div className="mt-3">
                  <div className="flex justify-between text-[10px] text-gray-600 mb-1">
                    <span>Confidence</span>
                    <span>{(c.confidence * 100).toFixed(0)}%</span>
                  </div>
                  <div className="h-1.5 bg-gray-800 rounded-full overflow-hidden">
                    <div
                      className="h-full rounded-full bg-gradient-to-r from-cyan-500 to-blue-500"
                      style={{ width: `${c.confidence * 100}%` }}
                    />
                  </div>
                </div>
              </div>

              {/* CTA */}
              <button className="px-4 py-2 rounded-lg bg-cyan-500/10 border border-cyan-500/30 text-cyan-400 text-sm hover:bg-cyan-500/20 transition-colors whitespace-nowrap">
                Investigate →
              </button>
            </div>
          </div>
        ))}
      </div>

      <Pagination
        currentPage={page}
        totalItems={cases?.length ?? 0}
        pageSize={PAGE_SIZE}
        onPageChange={setPage}
      />
    </div>
  );
}
