import { useEffect,useMemo,useRef,useState } from 'react';
import { Brain,Database,Download,FileJson,RefreshCcw,Sparkles,Upload } from 'lucide-react';
import { buildCorpus,downloadJson,downloadJsonl,getLatestCorpus,getQueryMemory,rememberQuery,retrieveCorpus,type CorpusSnapshot } from '../live/corpusEngine';
import { importJsonEvents } from '../live/jsonImport';

export default function CorpusLab(){
 const[corpus,setCorpus]=useState<CorpusSnapshot|null>(null);const[query,setQuery]=useState('');const[answer,setAnswer]=useState('');const[loading,setLoading]=useState(false);const[memory,setMemory]=useState<any[]>([]);const[importMsg,setImportMsg]=useState('');const importRef=useRef<HTMLInputElement>(null);
 const refresh=async()=>{setLoading(true);try{const c=await buildCorpus(true);setCorpus(c);setMemory(await getQueryMemory())}finally{setLoading(false)}};
 useEffect(()=>{getLatestCorpus().then(c=>c?setCorpus(c):refresh());getQueryMemory().then(setMemory)},[]);
 const results=useMemo(()=>corpus?retrieveCorpus(query,corpus.documents,12):[],[query,corpus]);
 const ask=async()=>{if(!query.trim()||!corpus)return;setLoading(true);const hits=retrieveCorpus(query,corpus.documents,12);const context=hits.map((h,i)=>`[${i+1}] ${h.doc.publishedAt} | ${h.doc.source} | ${h.doc.title}\n${h.doc.text}\nLocation: ${h.doc.location||h.doc.country||'unknown'} | Actors: ${h.doc.actors.join(', ')} | TLP: ${h.doc.tlp}`).join('\n\n');let out='';try{const r=await fetch('/api/lm',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({messages:[{role:'system',content:'Answer only from the supplied GHOTAM corpus evidence. Separate observed facts from inference. Cite evidence as [1], [2]. If evidence is insufficient, say so.'},{role:'user',content:`Question: ${query}\n\nGHOTAM CORPUS:\n${context}`}],temperature:.15,max_tokens:700})});if(r.ok){const d=await r.json();out=String(d?.choices?.[0]?.message?.content||d?.answer||'')}else throw new Error(String(r.status))}catch{out=hits.length?`Resultados recuperados localmente (${hits.length}).\n\n`+hits.slice(0,6).map((h,i)=>`[${i+1}] ${h.doc.title} — ${h.doc.source}`).join('\n'):'No hay evidencia suficiente en el corpus local.'}setAnswer(out);await rememberQuery(query,out,hits.map(h=>h.doc.id));setMemory(await getQueryMemory());setLoading(false)};
 const importJson=async(file?:File)=>{if(!file)return;setLoading(true);setImportMsg('');try{const parsed=JSON.parse(await file.text());const r=await importJsonEvents(parsed);setImportMsg(`Importados ${r.total}: ${r.inserted} nuevos · ${r.updated} actualizados · ${r.skipped} omitidos.`);await refresh()}catch(e){setImportMsg(e instanceof Error?e.message:'No se pudo importar el JSON.')}finally{setLoading(false);if(importRef.current)importRef.current.value=''}};
 const date=new Date().toISOString().slice(0,10);
 return <div className="intel-dashboard animate-slide-in"><div className="intel-page-head"><div><div className="eyebrow">GHOTAM / KNOWLEDGE CORPUS</div><h2>Corpus & AI Memory</h2><p>Exportación RAG · JSON/JSONL · importación de eventos · recuperación local · consultas grounded</p></div><button onClick={refresh} className="intel-action"><RefreshCcw className={loading?'animate-spin':''} size={14}/>REBUILD</button></div>
 <div className="intel-kpi-grid"><div className="intel-kpi"><span>Documents</span><strong>{corpus?.count||0}</strong></div><div className="intel-kpi"><span>Sources</span><strong>{new Set(corpus?.documents.map(d=>d.source)||[]).size}</strong></div><div className="intel-kpi"><span>Alternative</span><strong>{corpus?.documents.filter(d=>d.sourceClass==='alternative').length||0}</strong></div><div className="intel-kpi"><span>Geolocated</span><strong>{corpus?.documents.filter(d=>typeof d.lat==='number').length||0}</strong></div><div className="intel-kpi"><span>Memory</span><strong>{memory.length}</strong></div></div>
 <section className="intel-panel"><div className="flex items-center justify-between gap-3 flex-wrap"><div><div className="eyebrow">CORPUS PORTABILITY</div><h3>Import / Export AI dataset</h3><p className="intel-sub">Importa JSON externo, arrays de eventos, {`{events:[...]}`} o un corpus GHOTAM_CORPUS_V1. La importación hace merge y deduplicación; no borra la base existente.</p></div><div className="flex gap-2 flex-wrap"><button className="intel-action" onClick={()=>importRef.current?.click()}><Upload size={14}/>IMPORT JSON</button><input ref={importRef} type="file" accept="application/json,.json" hidden onChange={e=>importJson(e.target.files?.[0])}/><button className="intel-action" disabled={!corpus} onClick={()=>corpus&&downloadJson(`ghotam-corpus-${date}.json`,corpus)}><FileJson size={14}/>EXPORT JSON</button><button className="intel-action" disabled={!corpus} onClick={()=>corpus&&downloadJsonl(`ghotam-corpus-${date}.jsonl`,corpus.documents)}><Download size={14}/>EXPORT JSONL</button></div></div>{importMsg&&<div className="intel-note mt-3"><Database size={14}/><span>{importMsg}</span></div>}</section>
 <div className="intel-two-col"><section className="intel-panel"><div className="eyebrow">LOCAL RETRIEVAL + MINICPM</div><h3 className="flex items-center gap-2"><Brain size={14}/>Query corpus</h3><div className="mt-3 flex gap-2"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder="Ej: eventos nuevos sobre Ucrania y Rusia en las últimas horas" className="flex-1 bg-[#081019] border border-[#263545] px-3 py-2 text-xs outline-none"/><button onClick={ask} disabled={loading||!query.trim()} className="admin-primary"><Sparkles size={14}/>CONSULTAR</button></div>{answer&&<div className="mt-4 bg-black/20 border border-white/5 p-3 text-xs text-slate-300 whitespace-pre-wrap leading-relaxed">{answer}</div>}<div className="mt-4 space-y-2 max-h-80 overflow-auto">{query&&results.map(({doc,score})=><div key={doc.id} className="intel-row"><p className="text-xs text-slate-300">{doc.title}</p><div className="metric-strip"><span>{doc.source}</span><span>SCORE {score.toFixed(1)}</span><span>{doc.tlp}</span><span>{new Date(doc.publishedAt).toLocaleString()}</span></div></div>)}</div></section>
 <section className="intel-panel"><div className="eyebrow">CACHE MEMORY</div><h3 className="flex items-center gap-2"><Database size={14}/>Query history</h3><div className="mt-3 space-y-2 max-h-[520px] overflow-auto">{memory.slice(0,30).map(m=><button key={m.id} onClick={()=>{setQuery(m.query);setAnswer(m.answer)}} className="w-full text-left intel-row"><p className="text-xs text-slate-300">{m.query}</p><div className="metric-strip"><span>{new Date(m.at).toLocaleString()}</span><span>{m.docIds?.length||0} docs</span></div></button>)}{!memory.length&&<p className="text-xs text-slate-600">Aún no hay consultas guardadas.</p>}</div></section></div></div>;
}
