import { useEffect,useMemo,useState } from 'react';
import { Activity,AlertTriangle,Globe2,RefreshCcw,ShieldCheck,Radar,Sparkles,Network,TrendingUp } from 'lucide-react';
import { analyzeAll,type Analysis,type IntelRecord,type QuadrantKey,type SignalClass,type Tlp } from '../live/analysisEngine';

const tlpStyle:Record<Tlp,string>={
  'TLP:CLEAR':'border-gray-500/30 text-gray-300 bg-gray-500/10','TLP:GREEN':'border-green-500/30 text-green-300 bg-green-500/10','TLP:AMBER':'border-amber-500/30 text-amber-300 bg-amber-500/10','TLP:AMBER+STRICT':'border-orange-500/30 text-orange-300 bg-orange-500/10','TLP:RED':'border-red-500/30 text-red-300 bg-red-500/10'
};
const riskStyle:Record<string,string>={LOW:'text-slate-400',GUARDED:'text-cyan-400',ELEVATED:'text-yellow-400',HIGH:'text-orange-400',CRITICAL:'text-red-400'};
const signalLabel:Record<SignalClass,string>={established:'Established pattern','early-warning-plausible':'Early warning · plausible','early-warning-unusual':'Early warning · unusual','black-swan-candidate':'Black Swan candidate',anomalous:'Anomalous signal',speculative:'Speculative'};

export default function Dashboard(){
  const [raw,setRaw]=useState<any[]>([]);const[loading,setLoading]=useState(false);const[error,setError]=useState('');
  const load=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/rss',{headers:{accept:'application/json'}});if(!r.ok)throw new Error(`RSS API ${r.status}`);const d=await r.json();setRaw(Array.isArray(d?.events)?d.events:[])}catch(e){setRaw([]);setError(e instanceof Error?e.message:'RSS unavailable')}finally{setLoading(false)}};
  useEffect(()=>{load();const id=setInterval(load,300000);return()=>clearInterval(id)},[]);
  const analyzed=useMemo(()=>analyzeAll(raw),[raw]);
  const events=analyzed.map(x=>x.event);const mapped=events.filter(e=>typeof e.lat==='number'&&typeof e.lng==='number');
  const actors=useMemo(()=>{const m=new Map<string,number>();events.forEach(e=>e.actors.forEach(a=>m.set(a,(m.get(a)||0)+1)));return[...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,10)},[raw]);
  const quadrants=useMemo(()=>Object.fromEntries((['plausible-probable','plausible-unlikely','weak-probable','weak-unlikely'] as QuadrantKey[]).map(k=>[k,analyzed.filter(x=>x.analysis.quadrant===k)])) as Record<QuadrantKey,typeof analyzed>,[analyzed]);
  const signals=useMemo(()=>({established:analyzed.filter(x=>x.analysis.signalClass==='established'),plausible:analyzed.filter(x=>x.analysis.signalClass==='early-warning-plausible'),unusual:analyzed.filter(x=>x.analysis.signalClass==='early-warning-unusual'),black:analyzed.filter(x=>x.analysis.signalClass==='black-swan-candidate'),anomalous:analyzed.filter(x=>x.analysis.signalClass==='anomalous')}),[analyzed]);
  const tlps=useMemo(()=>Object.fromEntries((['TLP:CLEAR','TLP:GREEN','TLP:AMBER','TLP:AMBER+STRICT','TLP:RED'] as Tlp[]).map(t=>[t,events.filter(e=>e.tlp===t).length])) as Record<Tlp,number>,[events]);
  const highRisk=useMemo(()=>[...analyzed].sort((a,b)=>b.analysis.riskScore-a.analysis.riskScore).slice(0,12),[analyzed]);
  const cards=[{label:'Live Events',value:events.length,icon:Activity},{label:'Geolocated',value:mapped.length,icon:Globe2},{label:'High/Critical Risk',value:analyzed.filter(x=>x.analysis.riskScore>=6.5).length,icon:AlertTriangle},{label:'Early Warnings',value:signals.plausible.length+signals.unusual.length,icon:Radar},{label:'Black Swan candidates',value:signals.black.length,icon:Sparkles}];

  const Q=({title,subtitle,items}:{title:string;subtitle:string;items:{event:IntelRecord;analysis:Analysis}[]})=><div className="rounded-xl border border-white/10 bg-white/[.02] p-3 min-h-[210px]"><div className="flex justify-between gap-3"><div><b className="text-xs text-gray-200">{title}</b><p className="text-[10px] text-gray-600 mt-1">{subtitle}</p></div><span className="text-xl font-bold">{items.length}</span></div><div className="mt-3 space-y-2">{items.slice(0,4).map(({event,analysis})=><div key={event.id} className="border-t border-white/5 pt-2"><p className="text-[11px] text-gray-300 line-clamp-2">{event.title}</p><div className="flex flex-wrap gap-2 text-[9px] text-gray-600 mt-1"><span>PLS {Math.round(analysis.plausibility*100)}</span><span>PRB {Math.round(analysis.probability*100)}</span><span>NOV {Math.round(analysis.novelty*100)}</span><span className={riskStyle[analysis.riskLevel]}>RISK {analysis.riskScore.toFixed(1)}</span></div><span className="text-[9px] text-cyan-500/80">{signalLabel[analysis.signalClass]}</span></div>)}</div></div>;

  return <div className="space-y-6 animate-slide-in">
    <div className="flex items-center justify-between"><div><h2 className="text-2xl font-bold text-gray-100">Geopolitical Intelligence Dashboard</h2><p className="text-sm text-gray-500 mt-1">Unified scoring · risk · pattern matrix · early warning · provenance</p></div><button onClick={load} className="flex items-center gap-2 px-3 py-2 rounded-lg border border-[var(--aegis-border)] text-xs text-gray-400"><RefreshCcw className={`w-4 h-4 ${loading?'animate-spin':''}`}/>Refresh</button></div>{error&&<div className="aegis-card p-3 text-xs text-amber-300">{error}</div>}
    <div className="grid grid-cols-5 gap-4">{cards.map(c=><div key={c.label} className="aegis-card p-4"><div className="flex justify-between"><span className="text-[10px] uppercase text-gray-500">{c.label}</span><c.icon className="w-4 h-4 text-cyan-400"/></div><p className="text-3xl font-bold mt-3">{c.value}</p></div>)}</div>

    <div className="grid grid-cols-2 gap-6"><div className="aegis-card p-5"><div className="flex justify-between"><div><h3 className="text-sm font-semibold">Information Handling · TLP 2.0</h3><p className="text-xs text-gray-600 mt-1">Distribution control only. Public RSS remains TLP:CLEAR unless the source explicitly carries another valid label.</p></div><ShieldCheck className="w-5 h-5 text-cyan-400"/></div><div className="grid grid-cols-5 gap-2 mt-4">{(['TLP:CLEAR','TLP:GREEN','TLP:AMBER','TLP:AMBER+STRICT','TLP:RED'] as Tlp[]).map(t=><div key={t} className={`rounded-lg border p-2 ${tlpStyle[t]}`}><p className="text-[8px] font-mono">{t}</p><p className="text-xl font-bold">{tlps[t]}</p></div>)}</div></div>
      <div className="aegis-card p-5"><h3 className="text-sm font-semibold">Threat / Risk Classification</h3><p className="text-xs text-gray-600 mt-1">Risk is independent from TLP and combines impact, probability, confidence, momentum and severity.</p><div className="grid grid-cols-5 gap-2 mt-4">{(['LOW','GUARDED','ELEVATED','HIGH','CRITICAL'] as const).map(r=><div key={r} className="rounded-lg border border-white/10 p-2"><p className={`text-[9px] ${riskStyle[r]}`}>{r}</p><p className="text-xl font-bold">{analyzed.filter(x=>x.analysis.riskLevel===r).length}</p></div>)}</div></div></div>

    <div className="aegis-card p-5"><h3 className="text-sm font-semibold">Prospective Pattern Matrix</h3><p className="text-xs text-gray-600 mt-1 mb-4">Plausibility = pattern establishment. Probability = current activation. Novelty and impact surface anomalous warnings and Black Swan candidates.</p><div className="grid grid-cols-[90px_1fr_1fr] gap-3"><div></div><div className="text-center text-[10px] text-gray-500 uppercase">Poco probable</div><div className="text-center text-[10px] text-gray-500 uppercase">Probable</div><div className="flex items-center justify-center text-[10px] text-gray-500 uppercase">Plausible</div><Q title="Plausible / Poco probable" subtitle="Early warning plausible" items={quadrants['plausible-unlikely']}/><Q title="Plausible / Probable" subtitle="Established / active pattern" items={quadrants['plausible-probable']}/><div className="flex items-center justify-center text-[10px] text-gray-500 uppercase">Poco plausible</div><Q title="Poco plausible / Poco probable" subtitle="Speculative / anomalous / Black Swan candidate" items={quadrants['weak-unlikely']}/><Q title="Poco plausible / Probable" subtitle="Early warning unusual" items={quadrants['weak-probable']}/></div></div>

    <div className="grid grid-cols-3 gap-4">{[{label:'Established',v:signals.established.length,icon:TrendingUp},{label:'Early warning · plausible',v:signals.plausible.length,icon:Radar},{label:'Early warning · unusual',v:signals.unusual.length,icon:Network},{label:'Anomalous signals',v:signals.anomalous.length,icon:Activity},{label:'Black Swan candidates',v:signals.black.length,icon:Sparkles}].map(x=><div key={x.label} className="aegis-card p-4"><div className="flex justify-between"><span className="text-xs text-gray-400">{x.label}</span><x.icon className="w-4 h-4 text-cyan-400"/></div><p className="text-2xl font-bold mt-2">{x.v}</p></div>)}</div>

    <div className="grid grid-cols-2 gap-6"><div className="aegis-card p-5"><h3 className="text-sm font-semibold mb-3">Top Actors</h3><div className="space-y-2">{actors.map(([name,count])=><div key={name} className="flex justify-between text-xs"><span className="text-gray-300">{name}</span><span className="text-gray-600">{count}</span></div>)}</div></div><div className="aegis-card p-5"><h3 className="text-sm font-semibold mb-3">Highest Risk Events</h3><div className="space-y-2 max-h-80 overflow-auto">{highRisk.map(({event,analysis})=><div key={event.id} className="border-b border-white/5 pb-2"><div className="flex justify-between gap-3"><p className="text-xs text-gray-300">{event.title}</p><span className={`text-xs font-bold ${riskStyle[analysis.riskLevel]}`}>{analysis.riskScore.toFixed(1)}</span></div><p className="text-[9px] text-gray-600 mt-1">{analysis.riskLevel} · PLS {Math.round(analysis.plausibility*100)} · PRB {Math.round(analysis.probability*100)} · MOM {Math.round(analysis.momentum*100)} · IMP {Math.round(analysis.impact*100)} · {event.tlp}</p></div>)}</div></div></div>
  </div>;
}
