import { Outlet, NavLink } from 'react-router-dom';
import { LayoutDashboard,Network,Map,ShieldAlert,Activity,Clock,Search,Building2,Users,Terminal,Waves,ExternalLink,X,GraduationCap,Radio,Share2,Database,BookOpen,Bell } from 'lucide-react';
import { useEffect,useState } from 'react';
import SearchBar from './SearchBar';
import { getSourceMode,setSourceMode,type SourceMode } from '../live/sourceMode';
import { checkForNewEvents,primeEventIndex,type NewEventSummary } from '../live/eventAlerts';

const navItems=[
 {to:'/',icon:Radio,label:'Live Intelligence',code:'01'},{to:'/ontology',icon:Share2,label:'Ontology Live',code:'02'},{to:'/dashboard',icon:LayoutDashboard,label:'Dashboard',code:'03'},
 {to:'/admin',icon:Database,label:'Admin / CRUD',code:'04'},{to:'/corpus',icon:BookOpen,label:'Corpus / AI',code:'05'},{to:'/command-center',icon:Terminal,label:'Command Center',code:'06'},
 {to:'/risk-propagation',icon:Waves,label:'Risk Propagation',code:'07'},{to:'/map',icon:Map,label:'Facilities Map',code:'08'},{to:'/graph',icon:Network,label:'Graph Explorer',code:'09'},
 {to:'/cases',icon:ShieldAlert,label:'Risk Cases',code:'10'},{to:'/events',icon:Activity,label:'Events',code:'11'},{to:'/facilities',icon:Building2,label:'Facilities',code:'12'},{to:'/persons',icon:Users,label:'Persons',code:'13'},{to:'/timeline',icon:Clock,label:'Timeline',code:'14'},
];
export default function Layout(){
 const[searchOpen,setSearchOpen]=useState(false),[aboutOpen,setAboutOpen]=useState(false),[alertsOpen,setAlertsOpen]=useState(false);const[mode,setMode]=useState<SourceMode>(getSourceMode());const[alerts,setAlerts]=useState<NewEventSummary>({newEvents:[],minute:0,hour:0,day:0,lastCheckedAt:''});
 useEffect(()=>{let live=true;primeEventIndex().then(()=>{});const poll=()=>checkForNewEvents(true).then(s=>live&&setAlerts(s)).catch(()=>{});const id=setInterval(poll,60000);return()=>{live=false;clearInterval(id)}},[]);
 const changeMode=(m:SourceMode)=>{setMode(m);setSourceMode(m);window.location.reload()};
 return <div className="flex h-screen bg-[var(--aegis-bg)]">
  <aside className="w-56 bg-[#080d14] border-r border-[#1d2935] flex flex-col overflow-hidden">
   <div className="h-16 flex items-center px-4 gap-3 border-b border-[#1d2935]"><div className="w-7 h-7 border border-cyan-500/40 bg-cyan-500/[.06] flex items-center justify-center"><Network className="w-4 h-4 text-cyan-400"/></div><div><span className="text-[15px] font-semibold tracking-[.12em] text-slate-200">GHOTAM</span><div className="text-[8px] text-slate-600 tracking-[.22em]">INTELLIGENCE SYSTEM</div></div></div>
   <div className="px-4 pt-4 pb-2 text-[8px] font-mono tracking-[.16em] text-slate-700">WORKSPACES</div>
   <nav className="flex-1 overflow-auto">{navItems.map(item=><NavLink key={item.to} to={item.to} end={item.to==='/'} className={({isActive})=>`group grid grid-cols-[24px_18px_1fr] items-center px-3 py-2 gap-2 text-[11px] border-l-2 transition-colors ${isActive?'border-cyan-400 text-slate-100 bg-cyan-500/[.07]':'border-transparent text-slate-500 hover:text-slate-300 hover:bg-white/[.025]'}`}><span className="font-mono text-[8px] text-slate-700 group-hover:text-slate-500">{item.code}</span><item.icon className="w-3.5 h-3.5"/><span>{item.label}</span></NavLink>)}</nav>
   <div className="p-3 border-t border-[#1d2935]"><div className="flex items-center gap-2"><div className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse"/><span className="text-[9px] font-mono text-slate-600">LOCAL DB / READY</span></div><button onClick={()=>setAboutOpen(true)} className="mt-2 flex items-center gap-2 text-[9px] text-slate-700 hover:text-slate-400"><GraduationCap className="w-3 h-3"/>SYSTEM INFO</button></div>
  </aside>
  <div className="flex-1 flex flex-col overflow-hidden"><header className="min-h-14 bg-[#090f17]/95 border-b border-[#1d2935] flex items-center justify-between px-5 gap-4"><div><h1 className="text-[10px] font-semibold text-slate-400 uppercase tracking-[.18em]">Ontology-driven public source intelligence</h1><p className="text-[8px] font-mono text-slate-700 mt-1">RSS / TELEGRAM PUBLIC / OFFLINE DB / CORPUS / GEO / ANALYTICS</p></div><div className="flex items-center gap-2">
    <div className="flex border border-[#273747] bg-[#0c141e] p-0.5">{([['direct','DIRECTAS'],['alternative','ALTERNATIVAS'],['all','TODAS']] as [SourceMode,string][]).map(([m,label])=><button key={m} onClick={()=>changeMode(m)} className={`px-2.5 py-1 text-[8px] font-mono ${mode===m?'bg-cyan-500/15 text-cyan-300':'text-slate-600 hover:text-slate-400'}`}>{label}</button>)}</div>
    <div className="relative"><button onClick={()=>setAlertsOpen(v=>!v)} className={`relative flex items-center gap-2 px-3 py-1.5 border text-[9px] font-mono ${alerts.day?'border-amber-500/30 bg-amber-500/[.07] text-amber-300':'border-[#273747] bg-[#0c141e] text-slate-500'}`}><Bell className="w-3.5 h-3.5"/>NUEVOS{alerts.day>0&&<b className="text-[9px]">{alerts.day}</b>}</button>{alertsOpen&&<div className="absolute right-0 top-full mt-2 z-50 w-[390px] bg-[#080f17] border border-[#273747] shadow-2xl"><div className="grid grid-cols-3 gap-px bg-[#1d2935]"><div className="bg-[#0b121b] p-2"><span className="text-[8px] text-slate-600">MINUTO</span><b className="block text-sm text-cyan-300">{alerts.minute}</b></div><div className="bg-[#0b121b] p-2"><span className="text-[8px] text-slate-600">HORA</span><b className="block text-sm text-amber-300">{alerts.hour}</b></div><div className="bg-[#0b121b] p-2"><span className="text-[8px] text-slate-600">DÍA</span><b className="block text-sm text-orange-300">{alerts.day}</b></div></div><div className="max-h-80 overflow-auto">{alerts.newEvents.slice(0,10).map((e:any)=><div key={String(e.id)} className="p-3 border-b border-[#172330]"><small className="text-[8px] text-slate-600">{String(e.source||e.feedId||'source')} · {new Date(e.publishedAt).toLocaleString()}</small><p className="text-[10px] text-slate-300 mt-1 leading-snug">{String(e.title||e.description||'Nuevo evento')}</p></div>)}{!alerts.newEvents.length&&<div className="p-4 text-[10px] text-slate-600">Sin eventos nuevos desde la última comprobación.</div>}</div></div>}</div>
    <button onClick={()=>setSearchOpen(!searchOpen)} className="flex items-center gap-2 px-3 py-1.5 border border-[#273747] bg-[#0c141e] text-slate-500 text-[9px] font-mono"><Search className="w-3 h-3"/>SEARCH</button><div className="px-2.5 py-1.5 border border-emerald-500/20 bg-emerald-500/[.05] text-[8px] font-mono text-emerald-400">● LIVE</div></div></header>{searchOpen&&<SearchBar onClose={()=>setSearchOpen(false)}/>}<main className="flex-1 overflow-auto p-4"><Outlet/></main></div>
  {aboutOpen&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75" onClick={()=>setAboutOpen(false)}><div className="max-w-xl mx-4 aegis-card p-5" onClick={e=>e.stopPropagation()}><div className="flex justify-between gap-4"><div><div className="eyebrow">SYSTEM INFORMATION</div><h2 className="font-semibold text-gray-100">Ghotam Live Intelligence</h2><p className="text-xs text-gray-500 mt-1">Public-source + local-first intelligence workspace.</p></div><button onClick={()=>setAboutOpen(false)}><X className="w-4 h-4"/></button></div><p className="text-xs text-gray-400 mt-4 leading-relaxed">Eventos manuales, fotografías, corpus, snapshots RSS/Telegram y memoria de consultas se conservan localmente para operación offline.</p><a href="https://github.com/sergiogonza/ghotam" target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 mt-4 text-xs text-cyan-400">Repository <ExternalLink className="w-3 h-3"/></a></div></div>}
 </div>;
}
