import { useEffect,useMemo,useState } from 'react';
import { BookmarkPlus,Database,Plus,Search,Trash2,X } from 'lucide-react';
import { analyzeAll } from '../live/analysisEngine';
import { matchesAnalyticQuery } from '../live/analyticSearch';
import { loadCombinedIntel } from '../live/offlineStore';
import { addWatchItem,createWatchlist,deleteWatchlist,listWatchlists,removeWatchItem,WATCHLIST_CHANGED,type Watchlist } from '../live/watchlistStore';

export default function Watchlists(){
  const[sets,setSets]=useState<Watchlist[]>([]);const[selectedId,setSelectedId]=useState('');const[raw,setRaw]=useState<any[]>([]);const[query,setQuery]=useState('');const[newName,setNewName]=useState('');
  const reload=()=>{const next=listWatchlists();setSets(next);if(!selectedId&&next[0])setSelectedId(next[0].id)};
  useEffect(()=>{reload();loadCombinedIntel().then(setRaw).catch(()=>setRaw([]));const h=()=>reload();window.addEventListener(WATCHLIST_CHANGED,h);return()=>window.removeEventListener(WATCHLIST_CHANGED,h)},[]);
  const selected=sets.find(x=>x.id===selectedId)||null;
  const analyzed=useMemo(()=>analyzeAll(raw),[raw]);
  const results=useMemo(()=>analyzed.filter(x=>matchesAnalyticQuery(x,query)).slice(0,80),[query,analyzed]);
  const create=()=>{if(!newName.trim())return;const row=createWatchlist(newName);setNewName('');setSelectedId(row.id)};
  return <div className="intel-dashboard animate-slide-in"><div className="intel-page-head"><div><div className="eyebrow">OSDK-STYLE OBJECT SETS</div><h2>Watchlists / Object Sets</h2><p>Persistent analytic collections · entities · events · reusable monitoring sets</p></div></div>
    <div className="grid grid-cols-[300px_minmax(0,1fr)] gap-3 min-h-[650px]">
      <aside className="intel-panel"><div className="flex gap-2"><input value={newName} onChange={e=>setNewName(e.target.value)} onKeyDown={e=>e.key==='Enter'&&create()} placeholder="New object set..." className="flex-1 bg-[#071019] border border-[#263545] px-2 py-2 text-xs outline-none"/><button onClick={create} className="intel-action"><Plus size={13}/></button></div><div className="mt-4 space-y-2">{sets.map(set=><button key={set.id} onClick={()=>setSelectedId(set.id)} className={`w-full text-left p-3 border ${selectedId===set.id?'border-cyan-500/40 bg-cyan-500/[.05]':'border-white/5 bg-white/[.015]'}`}><div className="flex justify-between gap-3"><div><b className="text-xs text-gray-200">{set.name}</b><p className="text-[9px] text-gray-600 mt-1">{set.items.length} objects</p></div><Database size={14} className="text-cyan-500/60"/></div></button>)}</div></aside>
      <section className="space-y-3">{selected?<><div className="intel-panel"><div className="flex items-center justify-between"><div><div className="eyebrow">ACTIVE OBJECT SET</div><h3>{selected.name}</h3><p className="intel-sub">Updated {new Date(selected.updatedAt).toLocaleString()} · {selected.items.length} objects</p></div><button onClick={()=>{deleteWatchlist(selected.id);setSelectedId('')}} className="text-red-400 text-xs flex items-center gap-1"><Trash2 size={13}/>Delete set</button></div><div className="mt-3 flex flex-wrap gap-2">{selected.items.map(item=><div key={item.id} className="flex items-center gap-2 px-2 py-1 border border-cyan-500/20 bg-cyan-500/[.04] text-[10px] text-gray-300"><span className="text-cyan-500">{item.type}</span><span>{item.label}</span><button onClick={()=>removeWatchItem(selected.id,item.id)}><X size={11}/></button></div>)}</div></div>
        <div className="intel-panel"><div className="flex items-center gap-2 border border-[#263545] bg-[#071019] px-3 py-2"><Search size={14} className="text-gray-600"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search actor, country, pattern, black swan, early warning, high risk..." className="flex-1 bg-transparent outline-none text-xs"/></div><div className="mt-2 flex flex-wrap gap-1 text-[9px] text-slate-600"><span>TRY:</span>{['black swan','early warning','established','anomalous','high risk','plausible','high momentum'].map(t=><button key={t} onClick={()=>setQuery(t)} className="px-2 py-1 border border-white/5 hover:border-cyan-500/30 hover:text-cyan-400">{t}</button>)}</div><div className="mt-3 grid grid-cols-2 gap-2 max-h-[540px] overflow-auto">{results.map(({event,analysis})=><div key={event.id} className="p-3 border border-white/5 bg-white/[.015]"><p className="text-xs text-gray-200 line-clamp-2">{event.title}</p><p className="text-[9px] text-gray-600 mt-1">{event.country||'Global'} · {analysis.patternFamily} · {analysis.signalClass} · {analysis.riskLevel} {analysis.riskScore.toFixed(1)}</p><button onClick={()=>addWatchItem(selected.id,{id:`EVENT:${event.id}`,label:event.title,type:'Event',sourceId:event.id,properties:{country:event.country,patternFamily:analysis.patternFamily,signalClass:analysis.signalClass,riskLevel:analysis.riskLevel,riskScore:analysis.riskScore,plausibility:analysis.plausibility,probability:analysis.probability,novelty:analysis.novelty,momentum:analysis.momentum}})} className="mt-2 text-[9px] text-cyan-400 flex items-center gap-1"><BookmarkPlus size={12}/>Add to Object Set</button></div>)}</div></div></>:<div className="intel-panel text-sm text-gray-500">Create an Object Set to start monitoring events and entities.</div>}</section>
    </div></div>;
}
